# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ldc_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1181, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_10 = QtWidgets.QHBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setStyleSheet("text-align: left;\n"
"padding-left: 10;\n"
"padding-right: 10px;\n"
"border: 2px solid black;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(255, 255, 127);\n"
"font: 75 14pt \"MS Sans Serif\";")
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.verticalLayout_10)

        #############################################################################################################
        self.scroll = QtWidgets.QScrollArea()
        self.widget = QtWidgets.QWidget()

        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")

        usrData = [{"name": "Ashes"}, {"name": "Utkarsh"}, {"name": "Mondal"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}, {"name": "Utkarsh"}]
        for i in range(0, len(usrData)):
                self.usrHbox = QtWidgets.QHBoxLayout()
                self.usrHbox.setObjectName("hbox_" + str(i))
                _translate = QtCore.QCoreApplication.translate

                self.usrlabel = QtWidgets.QLabel(self.widget)
                self.usrlabel.setStyleSheet("text-align: left;\n"
                "padding-left: 10;\n"
                "padding-right: 10px;\n"
                "color: rgb(85, 0, 127);\n"
                "font: 75 11pt \"Verdana\";")
                self.usrlabel.setObjectName("usrlabel_" + str(i))
                self.usrlabel.setText(_translate("MainWindow", usrData[i]["name"].upper() + "_" + str(i) ))
                self.usrHbox.addWidget(self.usrlabel)

                self.msgPushButton = QtWidgets.QPushButton(self.widget)
                self.msgPushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.msgPushButton.setStyleSheet("font-size: 15px;\n"
                "border: 2px solid black;\n"
                "border-radius: 10px;\n"
                "padding: 4;\n"
                "color: rgb(85, 0, 127);\n"
                "background-color: rgb(85, 255, 255);")
                self.msgPushButton.setObjectName("msgPushButton_" + str(i))
                self.msgPushButton.setText(_translate("MainWindow", "M"))
                self.usrHbox.addWidget(self.msgPushButton)

                self.filePushButton = QtWidgets.QPushButton(self.widget)
                self.filePushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
                self.filePushButton.setStyleSheet("font-size: 15px;\n"
                "border: 2px solid black;\n"
                "border-radius: 10px;\n"
                "padding: 4;\n"
                "color: rgb(85, 0, 127);\n"
                "background-color: rgb(85, 255, 255);")
                self.filePushButton.setObjectName("filePushButton_" + str(i))
                self.filePushButton.setText(_translate("MainWindow", "F"))
                self.usrHbox.addWidget(self.filePushButton)

                self.usrHbox.setStretch(0, 5)
                self.usrHbox.setStretch(1, 1)
                self.usrHbox.setStretch(2, 1)
                self.verticalLayout_9.addLayout(self.usrHbox)

                self.usrline = QtWidgets.QFrame(self.centralwidget)
                self.usrline.setFrameShape(QtWidgets.QFrame.HLine)
                self.usrline.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.usrline.setObjectName("usrline_" + str(i))
                self.verticalLayout_9.addWidget(self.usrline)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)

        self.widget.setLayout(self.verticalLayout_9)
        #Scroll Area Properties
        self.scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll.setWidgetResizable(True)
        self.scroll.setWidget(self.widget)

        self.verticalLayout_5.addWidget(self.scroll)

        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 10)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("text-align: left;\n"
"padding: 3;\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border: 2px solid black;\n"
"color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_10.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("padding: 4;\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(255, 255, 127);\n"
"text-align: left;\n"
"border: 2px solid black;\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("text-align: left;\n"
"padding-left: 10;\n"
"padding-right: 10px;\n"
"color: rgb(85, 0, 127);\n"
"font: 75 11pt \"Verdana\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_17.addWidget(self.label_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("font-size: 15px;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 4;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_17.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("font-size: 15px;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 4;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_17.addWidget(self.pushButton_7)
        self.horizontalLayout_17.setStretch(0, 5)
        self.horizontalLayout_17.setStretch(1, 1)
        self.horizontalLayout_17.setStretch(2, 1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_17)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_18.addWidget(self.line_4)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setStyleSheet("text-align: left;\n"
"padding-left: 10;\n"
"padding-right: 10px;\n"
"color: rgb(85, 0, 127);\n"
"font: 75 11pt \"Verdana\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_16.addWidget(self.label_6)
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setStyleSheet("font-size: 15px;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 4;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_16.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("font-size: 15px;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 4;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_16.addWidget(self.pushButton_9)
        self.horizontalLayout_16.setStretch(0, 5)
        self.horizontalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.setStretch(2, 1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_16)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_18.addWidget(self.line_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setStyleSheet("text-align: left;\n"
"padding-left: 10;\n"
"padding-right: 10px;\n"
"color: rgb(85, 0, 127);\n"
"font: 75 11pt \"Verdana\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("font-size: 15px;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 4;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_14.addWidget(self.pushButton_12)
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("font-size: 15px;\n"
"border: 2px solid black;\n"
"border-radius: 10px;\n"
"padding: 4;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_14.addWidget(self.pushButton_11)
        self.horizontalLayout_14.setStretch(0, 5)
        self.horizontalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.setStretch(2, 1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_14)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.verticalLayout_18)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 10)
        self.verticalLayout_4.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setStyleSheet("text-align: left;\n"
"padding: 3;\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"border: 2px solid black;\n"
"color: rgb(85, 0, 127);\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("padding: 4;\n"
"padding-left: 10;\n"
"padding-right: 10;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(255, 255, 127);\n"
"text-align: left;\n"
"border: 2px solid black;\n"
"font: 75 11pt \"MS Sans Serif\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_11.addWidget(self.pushButton_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 10)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("text-align: left;\n"
"padding-left: 10;\n"
"padding-right: 10px;\n"
"border: 2px solid black;\n"
"color: rgb(85, 0, 127);\n"
"background-color: rgb(255, 255, 127);\n"
"font: 75 14pt \"MS Sans Serif\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.verticalLayout_15)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 7)
        self.verticalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1181, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CURRENT ONLINE USERS"))
        # self.label_3.setText(_translate("MainWindow", "ASHES"))
        # self.pushButton_4.setText(_translate("MainWindow", "M"))
        # self.pushButton_3.setText(_translate("MainWindow", "F"))
        # self.label_4.setText(_translate("MainWindow", "UTKARSH"))
        # self.pushButton_6.setText(_translate("MainWindow", "M"))
        # self.pushButton_5.setText(_translate("MainWindow", "F"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search Users"))
        self.pushButton.setText(_translate("MainWindow", "Search"))
        self.label_5.setText(_translate("MainWindow", "MONDAL"))
        self.pushButton_8.setText(_translate("MainWindow", "M"))
        self.pushButton_7.setText(_translate("MainWindow", "F"))
        self.label_6.setText(_translate("MainWindow", "AARYAK"))
        self.pushButton_10.setText(_translate("MainWindow", "M"))
        self.pushButton_9.setText(_translate("MainWindow", "F"))
        self.label_7.setText(_translate("MainWindow", "ANURAG"))
        self.pushButton_12.setText(_translate("MainWindow", "M"))
        self.pushButton_11.setText(_translate("MainWindow", "F"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Search Files"))
        self.pushButton_2.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "DOWNLOADS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
